#!/bin/bash

#: * `git-gc`:
#:
#: Perform git gc on all brew taps and brew core repository.
#: not dependencies of another installed formula.

set -o errexit
set -o nounset

get_repo_size() {
  /usr/bin/du -sk .git | /usr/bin/awk '{print $1}'
}

options="$@"
total_previous_size=0
total_current_size=0

for dir in "$HOMEBREW_REPOSITORY" "$HOMEBREW_LIBRARY_PATH"/../Taps/*/*; do
  [[ -d "$dir/.git" ]] || continue
  cd "$dir" || continue

  echo "$dir"

  previous_size=$(get_repo_size)
  (( total_previous_size += previous_size ))

  echo "$ git gc ${options}"
  /usr/bin/git gc ${options}

  current_size=$(get_repo_size)
  (( total_current_size += current_size ))

  echo "${previous_size}KB -> ${current_size}KB"
  echo
done
echo "Total: ${total_previous_size}KB -> ${total_current_size}KB"
